# Generated by Django 5.0.4 on 2024-04-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NATO_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year_joined', models.PositiveIntegerField()),
                ('military_capability', models.CharField(max_length=100)),
                ('budget_allocation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='member_photos/')),
            ],
        ),
    ]
